In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import StandardScaler

In [2]:
# Dados fictícios para 5 produtos
data = {
    'Product': ['Smartphone1', 'Smartphone2', 'Smartphone3', 'Smartphone4', 'Smartphone5'],
    'Brand': ['Samsung', 'Apple', 'OnePlus', 'Samsung', 'Xiaomi'],
    'OS': ['Android', 'iOS', 'Android', 'Android', 'Android'],
    'RAM': [8, 4, 6, 8, 6],
    'Storage': [128, 64, 128, 256, 128],
    'Camera': [12, 16, 12, 20, 16],
    'Display': [6.2, 5.8, 6.5, 6.1, 6.4],
    'Battery': [4000, 3200, 4300, 4000, 4500],
    'Price': [1000, 2200, 900, 1100, 800]
}

df = pd.DataFrame(data)

In [3]:
print(pd.DataFrame(data))

       Product    Brand       OS  RAM  Storage  Camera  Display  Battery  \
0  Smartphone1  Samsung  Android    8      128      12      6.2     4000   
1  Smartphone2    Apple      iOS    4       64      16      5.8     3200   
2  Smartphone3  OnePlus  Android    6      128      12      6.5     4300   
3  Smartphone4  Samsung  Android    8      256      20      6.1     4000   
4  Smartphone5   Xiaomi  Android    6      128      16      6.4     4500   

   Price  
0   1000  
1   2200  
2    900  
3   1100  
4    800  


In [4]:
# Padronizando as features numéricas
numerical_features = ['RAM', 'Storage', 'Camera', 'Display', 'Battery', 'Price']
scaler = StandardScaler()
df[numerical_features] = scaler.fit_transform(df[numerical_features])

# Codificar features categóricas
df_encoded = pd.get_dummies(df[['Brand', 'OS']])

# Combinando features
df_final = pd.concat([df_encoded, df[numerical_features]], axis=1)

In [5]:
print(df_final)

   Brand_Apple  Brand_OnePlus  Brand_Samsung  Brand_Xiaomi  OS_Android  \
0        False          False           True         False        True   
1         True          False          False         False       False   
2        False           True          False         False        True   
3        False          False           True         False        True   
4        False          False          False          True        True   

   OS_iOS       RAM   Storage    Camera   Display   Battery     Price  
0   False  1.069045 -0.204124 -1.069045  0.000000  0.000000 -0.392232  
1    True -1.603567 -1.224745  0.267261 -1.632993 -1.807016  1.961161  
2   False -0.267261 -0.204124 -1.069045  1.224745  0.677631 -0.588348  
3   False  1.069045  1.837117  1.603567 -0.408248  0.000000 -0.196116  
4   False -0.267261 -0.204124  0.267261  0.816497  1.129385 -0.784465  


In [6]:
# Calculate cosine similarity matrix
cos_sim = cosine_similarity(df_final)

# Define the selected product index (Product 1 in this case)
selected_product_index = 0

# Get the similarity scores for the selected product
similarity_scores = cos_sim[selected_product_index]

In [7]:
print(cos_sim)

[[ 1.         -0.2982528   0.42658685  0.1751697   0.16875536]
 [-0.2982528   1.         -0.42355302 -0.26747095 -0.47906696]
 [ 0.42658685 -0.42355302  1.         -0.2447479   0.59474206]
 [ 0.1751697  -0.26747095 -0.2447479   1.          0.08862471]
 [ 0.16875536 -0.47906696  0.59474206  0.08862471  1.        ]]


In [8]:
print(similarity_scores)

[ 1.         -0.2982528   0.42658685  0.1751697   0.16875536]
